name: Generate Contributions Snake

on:
  schedule:
    - cron: "0 0 * * *"  # daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "snake"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: AjaykumarBLUEWHALE
          outputs: |
            dist/snake.svg

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        if: success()
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
